name: Build Test

on:
  push:

jobs:
  build-native-components:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Download webOS NDK
      run: wget -q https://github.com/webosbrew/meta-lg-webos-ndk/releases/download/1.0.g-rev.4/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh -P ${{github.workspace}}/temp

    - name: Install webOS NDK
      run: chmod 755 ${{github.workspace}}/temp/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh && sudo ${{github.workspace}}/temp/webos-sdk-x86_64-armv7a-neon-toolchain-1.0.g.sh -y

    - name: Initialize NDK Environments
      run: env -i bash -c '. /opt/webos-sdk-x86_64/1.0.g/environment-setup-armv7a-neon-webos-linux-gnueabi && env' >> $GITHUB_ENV

    - name: Create build directories
      run: |
        mkdir ${{github.workspace}}/hyperion-webos/build

    - name: Build hyperion-webos
      working-directory: ${{github.workspace}}/hyperion-webos/build
      shell: bash
      run: cmake .. && make
    
    - name: List files
      run: find .

    - name: Upload native components artifacts
      uses: actions/upload-artifact@v2
      with:
        name: webos_libs
        path: ${{github.workspace}}/hyperion-webos/build/hyperion-webos

    - name: Upload native components artifacts
      uses: actions/upload-artifact@v2
      with:
        name: webos_libs
        path: ${{github.workspace}}/servicenative/piccapautostart

    - name: Upload native components artifacts
      uses: actions/upload-artifact@v2
      with:
        name: webos_libs
        path: ${{github.workspace}}/servicenative/services.json

    - name: Upload native components artifacts
      uses: actions/upload-artifact@v2
      with:
        name: webos_libs
        path: ${{github.workspace}}/hyperion-webos/build/*_backend.so

  build-piccap:
    runs-on: ubuntu-latest
    needs: build-native-components

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install webOS CLI
        run: |
          sudo npm install -g @webosose/ares-cli

      - name: Install dependencies
        working-directory: ${{github.workspace}}
        run: npm install

      - name: Build App
        working-directory: ${{github.workspace}}
        run: npm run build

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: webos_libs
          path: webos_libs

      - name: List files
        run: find .

      - name: Copy native module
        run: |
          mkdir -p ./servicenative
          chmod +x webos_libs/hyperion-webos webos_libs/piccapautostart
          cp webos_libs/hyperion-webos ./servicenative/hyperion-webos
          cp webos_libs/libdile_vt_backend.so ./servicenative/libdile_vt_backend.so
          cp webos_libs/libvtcapture_backend.so ./servicenative/libvtcapture_backend.so
          cp webos_libs/piccapautostart ./servicenative/piccapautostart

      - name: Package
        run: mkdir build && ares-package ./dist/frontend/ ./servicenative -o ./build

      - name: List files
        run: find . && find ./build

      - name: Upload piccap ipk
        uses: actions/upload-artifact@v2
        with:
          name: piccap_ipk
          path: |
            build/*.ipk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build/*.ipk